name       : st
version    : 0.8.4
release    : 1
source     :
    - http://dl.suckless.org/st/st-0.8.4.tar.gz : d42d3ceceb4d6a65e32e90a5336e3d446db612c3fbd9ebc1780bc6c9a03346a6
    - https://st.suckless.org/patches/xresources/st-xresources-20200604-9ba7ecf.diff : 5be9b40d2b51761685f6503e92028a7858cc6571a8867b88612fce8a70514d5b
license    : MIT
component  : system.utils
summary    : A simple virtual terminal emulator for X
description: |
    A simple virtual terminal emulator for X.
builddeps  :
    - pkgconfig(xft)
rundeps :
    - tmux
setup      : |
    %patch -p1 < $sources/st-xresources-20200604-9ba7ecf.diff
    %patch -p0 < $pkgfiles/0001-terminfo.patch
    %patch -p0 < $pkgfiles/0002-config.def.h.patch
build      : |
    %make X11INC=/usr/include/X11 X11LIB=/usr/lib/X11
install    : |
    %make_install PREFIX=/usr
    install -D -m644 $workdir/st.info $installdir/usr/share/st/st.info
    install -D -m644 $pkgfiles/st.desktop $installdir/usr/share/applications/st.desktop
